In [49]:
import numpy as np
import random

In [71]:
a = np.array([[-1,2],[2,3]])
b = np.array([[33],[55]])

In [51]:
np.concatenate((a, b), axis=1)

array([[ 1,  2, 33],
       [ 2,  3, 55]])

In [52]:
random.shuffle(a)

In [53]:
a

array([[1, 2],
       [2, 3]])

In [74]:
a*(a>0)

array([[0, 2],
       [2, 3]])

In [58]:
np.random.random_sample([4])

array([ 0.96697947,  0.21990619,  0.40384783,  0.72578308])

In [64]:
np.eye(10)[[4,5,7]]

array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.]])

In [65]:
a = np.array([[1,1,1,1,0,1]])

In [67]:
np.sum(a)**2

25

In [70]:
a.max()

1

In [77]:
-np.nan

nan

In [83]:
a = np.array([1,2,3,4,5])

In [84]:
b = np.array([1,3,3,3,3])

In [90]:
num = np.equal(a,b).astype("int32")

array([1, 0, 1, 0, 0], dtype=int32)

In [1]:
import numpy as np
import h5py
import random
with h5py.File('../Code/Dataset/train_128.h5','r') as H:data = np.copy(H['data'])[:-100]
with h5py.File('../Code/Dataset/train_label.h5','r') as H: label = np.copy(H['label'])[:-100]
label = np.eye(10)[label]

min_ = data.min(axis=0)
data = data+abs(min_)

max_ = data.max(axis=0)
data = data/max_

OSError: Unable to open file (Unable to open file: name = '../code/dataset/train_128.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

In [2]:
from keras.models import Sequential

model = Sequential()

Using TensorFlow backend.


In [3]:
from keras.layers import Dense
import keras

model.add(Dense(units=96, activation='tanh', input_dim=128))
model.add(Dense(units=32, activation='tanh'))
model.add(Dense(units=10, activation='softmax'))

In [4]:
# model.compile(loss='categorical_crossentropy',
#               optimizer='sgd',
#               metrics=['accuracy'])
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.001, momentum=0.9, nesterov=True),metrics=['accuracy'])

In [ ]:
model.predict()

In [5]:
model.fit(data, label, epochs=50, batch_size=32)

Epoch 1/50
59900/59900 [==============================] - 5s - loss: 1.9278 - acc: 0.4491     
Epoch 2/50
59900/59900 [==============================] - 4s - loss: 0.9872 - acc: 0.7320     
Epoch 3/50
59900/59900 [==============================] - 4s - loss: 0.6835 - acc: 0.7783     
Epoch 4/50
59900/59900 [==============================] - 4s - loss: 0.5839 - acc: 0.8005     
Epoch 5/50
59900/59900 [==============================] - 4s - loss: 0.5327 - acc: 0.8156     
Epoch 6/50
59900/59900 [==============================] - 4s - loss: 0.5029 - acc: 0.8243     
Epoch 7/50
59900/59900 [==============================] - 4s - loss: 0.4844 - acc: 0.8314     
Epoch 8/50
59900/59900 [==============================] - 4s - loss: 0.4719 - acc: 0.8344     
Epoch 9/50
59900/59900 [==============================] - 4s - loss: 0.4627 - acc: 0.8376     
Epoch 10/50
59900/59900 [==============================] - 4s - loss: 0.4557 - acc: 0.8391     
Epoch 11/50
59900/59900 [========================

KeyboardInterrupt: 

In [194]:
d = np.random.binomial(n = 1, p = 0.5, size = 5)

In [209]:
a = np.array([[1,2,3,4,5],[11,22,33,44,55]]).astype("float32")

In [210]:
np.multiply(a,d)

array([[  0.,   2.,   3.,   0.,   5.],
       [  0.,  22.,  33.,   0.,  55.]])

In [197]:
d

array([0, 1, 1, 0, 1])

In [198]:
a.shape

(2, 5)

In [221]:
np.subtract(a,a)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)